image:
  repository: eranzaksh/moviesapp
  tag: "da37dbd"
service:
  enabled: true
  type: ClusterIP
  targetPort: 5005
  port: 443
spec:
  replicaCount: 1

app:
  name: web-app
  namespace: web-app
  ingress:
    enabled: true
    host: eranapp.duckdns.org
    className: nginx
    annotations: {cert-manager.io/cluster-issuer: "letsencrypt-prod"}
