image:
  repository: eranzaksh/leumi
  tag: "e479a571afc4ad3860b8d287bd0e60bd2eaf6bba"
service:
  enabled: true
  type: ClusterIP
  targetPort: 5000
  port: 443
spec:
  replicaCount: 1
app:
  name: "web-app"
  namespace: web-app
  ingress:
    enabled: true
    host: eranapp.duckdns.org
    className: nginx
    annotations: {cert-manager.io/cluster-issuer: "letsencrypt-prod"}
